// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYHaQ52dd7e6290zyPIJ-wVPDJ0CKYpvg',
    appId: '1:894830943603:web:314e19bf5111d264d9f906',
    messagingSenderId: '894830943603',
    projectId: 'vitalfit-8edfe',
    authDomain: 'vitalfit-8edfe.firebaseapp.com',
    storageBucket: 'vitalfit-8edfe.firebasestorage.app',
    measurementId: 'G-YWPRSGTQPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK8Ieg2_JQEigLBOIF0ZpjKFVAsGdHSjE',
    appId: '1:894830943603:android:363171276d7f49e5d9f906',
    messagingSenderId: '894830943603',
    projectId: 'vitalfit-8edfe',
    storageBucket: 'vitalfit-8edfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYDZ_Fvesqrw17VGQHUOFDHK9ejmp8QY0',
    appId: '1:894830943603:ios:ef0bcf3399eb7147d9f906',
    messagingSenderId: '894830943603',
    projectId: 'vitalfit-8edfe',
    storageBucket: 'vitalfit-8edfe.firebasestorage.app',
    iosBundleId: 'nicolas.cloudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYDZ_Fvesqrw17VGQHUOFDHK9ejmp8QY0',
    appId: '1:894830943603:ios:93ee84aa94f21e54d9f906',
    messagingSenderId: '894830943603',
    projectId: 'vitalfit-8edfe',
    storageBucket: 'vitalfit-8edfe.firebasestorage.app',
    iosBundleId: 'com.vitalfit.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYHaQ52dd7e6290zyPIJ-wVPDJ0CKYpvg',
    appId: '1:894830943603:web:5e69a1a5e5f85093d9f906',
    messagingSenderId: '894830943603',
    projectId: 'vitalfit-8edfe',
    authDomain: 'vitalfit-8edfe.firebaseapp.com',
    storageBucket: 'vitalfit-8edfe.firebasestorage.app',
    measurementId: 'G-7GQ6Q5Y3F4',
  );
}
